### ISSUE TITLE
Deployment Error: ResourceDeploymentFailure

### ISSUE THREAD

**Issue by josh-klassen** [elastic/azure-marketplace#163] opened 2018-01-22 16:33 UTC
When Deploying with azure template all master and data nodes fail with the following error:
```
[22012018-14:09:48] [port_forward] installed iptables-persistent
[22012018-14:09:48] [port_forward] port forwarding configured
[22012018-14:09:53] [wait_for_started] Seeing if node is up for the after sleeping 5 seconds, retry 1/30
[22012018-14:09:58] [wait_for_started] Seeing if node is up for the after sleeping 5 seconds, retry 2/30
...
[22012018-14:12:20] [wait_for_started] Seeing if node is up for the after sleeping 5 seconds, retry 29/30
[22012018-14:12:25] [wait_for_started] Seeing if node is up for the after sleeping 5 seconds, retry 30/30
[22012018-14:12:25] [wait_for_started] never saw elasticsearch go up locally
```
#125 is the same issue from months ago with no specified resolution.

[arm-install.log](https://github.com/elastic/azure-marketplace/files/1652741/arm-install.log)
[stderr.log](https://github.com/elastic/azure-marketplace/files/1652745/stderr.log)

**Comment by josh-klassen** [comment] 2018-01-29 14:49
@russcam is there any word on this?

**Comment by russcam** [comment] 2018-02-01 00:53
There's nothing in the logs to indicate what the issue may have been @josh-klassen. This may be an intermittent network issue. Do you also have an Elasticsearch log file?

**Comment by josh-klassen** [comment] 2018-02-15 20:12
These servers have been removed as they were just tests so unfortunately I do not have the Elasticsrearch log files. Is there no other way this could occur other than a network issue? I was able to reproduce the error several times so it seems unlikely that it was intermittent.

**Comment by russcam** [comment] 2018-02-16 02:53
It could potentially be for a number of different reasons. If you were able to reproduce it several times however, it seems reasonable that it's either

1. an issue in the ARM template
2. an issue in the deployment scripts on the target environment
3. an issue in a particular Azure region

Testing the template didn't yield any issues at the point of release, but it is possible that testing has missed potential issues. The logs would allow us to determine what this is, so without them, it's not possible to definitively say.

I have been working on adding support for Elasticsearch and Kibana 6.x to the template and have opened PR #165 for review to merge this into `master` and then release to the Marketplace. This PR includes a number of improvements to the template which may include a fix for the underlying issue that you've been seeing. Would you like to try a deployment from that branch? The following PowerShell script would be able to help with this

```powershell
$ErrorActionPreference = "Stop"

function PromptCustom($title, $optionValues, $optionDescriptions)
{
    Write-Host $title
    Write-Host
    $a = @()
    for($i = 0; $i -lt $optionValues.Length; $i++){
        Write-Host "$($i+1))" $optionDescriptions[$i]
    }
    Write-Host

    while($true)
    {
        Write-Host "Choose an option: "
        $option = Read-Host
        $option = $option -as [int]

        if($option -ge 1 -and $option -le $optionValues.Length)
        {
            return $optionValues[$option-1]
        }
    }
}

function Prompt-Subscription() {
    # Choose subscription. If there's only one we will choose automatically
    $subs = Get-AzureRmSubscription
    $subscriptionId = ""

    if($subs.Length -eq 0) {
        Write-Error "No subscriptions bound to this account."
        return
    }

    if($subs.Length -eq 1) {
        $subscriptionId = $subs[0].Id
    }
    else {
        $subscriptionChoices = @()
        $subscriptionValues = @()

        foreach($subscription in $subs) {
            $subscriptionChoices += "$($subscription.Name) ($($subscription.Id))";
            $subscriptionValues += ($subscription.Id);
        }

        $subscriptionId = PromptCustom "Choose a subscription" $subscriptionValues $subscriptionChoices
    }

    return $subscriptionId
}

Write-Host "Please Login"
Login-AzureRmAccount
$subscriptionId = Prompt-Subscription
Select-AzureRmSubscription -SubscriptionId $subscriptionId

# These will target the latest commit in feature/6.x branch
$templateBranch = "feature/6.x"
$templateUrl = "https://raw.githubusercontent.com/elastic/azure-marketplace/$templateBranch/src"
$elasticTemplate = "$templateUrl/mainTemplate.json"

# change the resource group location
$location = "Australia Southeast"

# name the resource group
$resourceGroup = "my-6x-resource-group"
$name = $resourceGroup

# change any parameters here that you wish using
# https://github.com/elastic/azure-marketplace/tree/feature/6.x#parameters
$clusterParameters = @{
    # DO NOT CHANGE artifactsBaseUrl
    "artifactsBaseUrl"= $templateUrl
    "esVersion" = "6.2.1"
    "esClusterName" = "es"
    # The Ubuntu admin user for VMs
    "adminUsername" = "russ"
    "authenticationType" = "password"
    "adminPassword" = "Password1234"
    "securityAdminPassword" = "Password123"
    "securityBootstrapPassword" = "Password123"
    "securityReadPassword" = "Password123"
    "securityKibanaPassword" = "Password123"
    "securityLogstashPassword" = "Password123"
}

Write-Host "[$(Get-Date -format 'u')] Deploying cluster"
New-AzureRmResourceGroup -Name $resourceGroup -Location $location
$deployment = New-AzureRmResourceGroupDeployment -Name $name `
                              -ResourceGroupName $resourceGroup `
                              -TemplateUri $elasticTemplate `
                              -TemplateParameterObject $clusterParameters
Write-Host "[$(Get-Date -format 'u')] Deployed cluster"

# Open a web browser with the Kibana IP and port after successful deployment
Start-Process $deployment.Outputs.kibana.Value
```

Let me know how you get on

**Comment by russcam** [comment] 2018-02-20 07:45
@josh-klassen #165 is now merged into master if you'd like to try deploying it from there. This version of the template is in the process of going live on the Azure Marketplace now. I'll update when it's live.

**Comment by josh-klassen** [comment] 2018-02-20 14:14
@russcam looks like the deployment still didn't work using the new template you posted. The issue seems to be the same as the issue we have when we deploy the elasticsearch manually. None of the node seem to be able to find one another. I have attached the log files for the latest deployment.

[stdout.log](https://github.com/elastic/azure-marketplace/files/1740341/stdout.log)
[arm-install.log](https://github.com/elastic/azure-marketplace/files/1740342/arm-install.log)
[elk-cluster.log](https://github.com/elastic/azure-marketplace/files/1740343/elk-cluster.log)
[stderr.log](https://github.com/elastic/azure-marketplace/files/1740344/stderr.log)

**Comment by russcam** [comment] 2018-02-20 23:45
@josh-klassen looking at the logs now

**Comment by russcam** [comment] 2018-02-21 01:00
@josh-klassen Do you have the complete `arm-install.log`? It looks to only be part of it, starting at `[setup_bootstrap_password] `. 

Nothing stands out in the logs provided. I have some further questions:

1. Could you provide the `arm-install.log` and the contents of `/var/log/monit.log` for `pelkmaster-0` VM
2. Are you updating an existing resource group, or deploying to a new resource group?
3. Are you using your own DNS servers?

    The ARM template assumes that DNS resolution is performed by Azure, which [provides hostname or FQDN name resolution for VMs located in the same VNet](https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-name-resolution-for-vms-and-role-instances).

    If you're using your own internal DNS servers, these need to be configured to resolve hostnames correctly. This can be achieved by [forwarding DNS queries to Azure to resolve using hostnames](https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-name-resolution-for-vms-and-role-instances#name-resolution-using-your-own-dns-server).

**Comment by josh-klassen** [comment] 2018-02-21 14:03
The logs attached are the complete logs from pelkmaster-0.

When deploying from the azuremarketplace we are create a new resource group just for this deployment. We are using our own DNS servers. I will have to check with a few others on the team regarding the hostname resolution setup.

Thanks let me know if those logs show anything.

[arm-install.log](https://github.com/elastic/azure-marketplace/files/1744213/arm-install.log)
[monit.log](https://github.com/elastic/azure-marketplace/files/1744214/monit.log)

**Comment by josh-klassen** [comment] 2018-02-21 15:07
@russcam I was able to check into a few DNS things. We do not use Azure to resolve the hostnames we currently rely on our own DNS servers and records. There does not seem to be a way within the templates to provide DNS servers to resolve on building the new VMs so this would need to be a manual process during a deployment after a failed deployment. I am trying to add correct DNS records and listings on these servers so they resolve and see if the nodes connect as expected at that point.

**Closed** 2018-02-21 16:04 UTC

**Comment by russcam** [comment] 2018-02-22 04:16
Thanks for getting back @josh-klassen. The issue is related to DNS.

> There does not seem to be a way within the templates to provide DNS servers to resolve on building the new VMs so this would need to be a manual process during a deployment after a failed deployment. I am trying to add correct DNS records and listings on these servers so they resolve and see if the nodes connect as expected at that point.

> It seems like this azure marketplace deployment of Elasticsearch will not work with how we do things. 

I think It'd be very tricky/unfeasible to automate this as part of the template. It may save you a lot of development effort though to fork this template and include the changes needed to set up your own DNS servers, possibly using [cloud-init](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/using-cloud-init).
