### ISSUE TITLE
storageAccounts folder is deleted in the repository

### ISSUE THREAD

**Issue by vijayaramb** [elastic/azure-marketplace#64] opened 2016-10-21 21:44 UTC
Kindly get back the storageAccounts folder which has the json files for new and existing storage account creations. This made the deployment fail now. Could you include the storageAccounts folder

**Comment by russcam** [comment] 2016-10-22 01:01
@vijayaramb The existing and new storage account deployment templates have been removed because there are issues with the Azure Marketplace when a nested linked template uses the outputs of another nested linked template as input parameters; this causes preflight validation checks for core quota limits to not fire and is a known issue for Microsoft. Additionally, Microsoft has also indicated that the use of the `listkeys()` function within the template will also cause preflight checks to fail.

Preflight validation checks are incredibly important as most template deployment failures reported are related to exceeding core quota limits, hence we want to ensure that they are firing.

I would like to include using a new or existing storage account for the Azure Cloud plugin again in the future but in the meantime, they won't be included in the template for the reasons outlined above.

If you have deployed a version of the template that uses them however, you can continue to deploy the same version of the template by 

1) [Forking the repository](https://help.github.com/articles/fork-a-repo/) and cloning locally

```sh
git clone git@github.com:elastic/azure-marketplace.git
```

2) checking out the tagged release version (or commit) of interest

```sh
git checkout tags/1.5.0 -b storageaccounts
```

for example, here, release `1.5.0` contains the storage accounts that you are interested in

3) Ensure all npm modules are installed (you will need [node installed](https://nodejs.org/en/))

```sh
npm install
```

4) Add a `.test.json` file in the `build` directory with your Azure credentials. This is git ignored to not be checked into github.

5) update the url links in templates to point to your new branch

```sh
npm run links -- --branch storageaccounts
```

This will update all template artifact url links to point to the storageaccounts branch. 

At this point, you'll also need to update urls to point to your forked repository (I'll add this to the gulp task to make it easier in future). Easiest way to do this will be to 

replace all `/elastic/azure-marketplace/` with `/<your github account>/azure-marketplace/`, so for me, this is `/russcam/azure-marketplace/`

replace all `%2Felastic%2Fazure-marketplace%2F` with `%2F<your github account>%2Fazure-marketplace%2F`, so for me, this is `%2Frusscam%2Fazure-marketplace%2F`

replace all `\/elastic\/azure\-marketplace\/` with `\/<your github account>\/azure\-marketplace\/`

replace all `%2Felastic%2Fazure\-marketplace%2F` with `%2F<your github account>%2Fazure\-marketplace%2F`

6) Add and commit changes

```sh
git add .
git commit -m "Update links"
```

7) Push your branch back up to your forked repository

```sh
git push -u origin storageaccounts
```

8) deploying from your repository using the [Command Line Deploy instructions](https://github.com/elastic/azure-marketplace#command-line-deploy). Be sure to fill in `parameters/password.parameters.json` with your deployment values

```sh
azure group deployment create --template-uri https://raw.githubusercontent.com/<your github account>/azure-marketplace/storageaccounts/src/mainTemplate.json --parameters-file parameters/password.parameters.json -g <resource group name>
```

**Closed by russcam** 2016-10-22 01:01 UTC

**Comment by Mpdreamz** [comment] 2016-10-23 09:06
Step 4 is only required if you want to run our automated testing commands on your fork, please be super careful with your credentials. For now i'd recommend not to set this.

**Comment by vijayaramb** [comment] 2016-10-31 20:19
hi,
It seems the root template is still looking for online url template of storage. Since you guys removed that storage jsons i am still facing issue.
I tried to clone the whole repository and uploaded all the scripts and templates as it to my own blob and used that url as the template base url. now i got rid of storage json issue and everything got deployed perfectly. 
Finally i got the below values as output. But the problem is i cann't access the kibana url, neither cann't access the elastic search data node end point (which is nothing but the load balancer url) through sense plug-in in chrome. I configured load balancer as external. 

Kindly let me know what i am doing wrong.

Everything works like a charm when done in UI. But all i need is the templates and scripts.

OutputsString           : 
                          Name             Type                       Value     
                          ===============  =========================  ==========
                          loadbalancer     String                     http://lb-3ljislfm57zr2.eastus2.cloudapp.azure.com:9200
                          kibana           String                     http://kb-3ljislfm57zr2.eastus2.cloudapp.azure.com:5601
                          jumpbox-ssh      String                     N/A

**Comment by russcam** [comment] 2016-10-31 22:41
I've not seen any issues with the root template in `master` looking for the storage account templates; Can you post the `artifactsBaseUrl` that is in the template you are running? Did you try the instructions I posted, and did they work for you? 

Are you running the template against an existing resource group where you have already deployed a cluster using a specific version of the template?

If you can post a reproducible example, it would really help.

You won't be able to access any data nodes directly, but if you have deployed an external load balancer, then you will be able to access the cluster through the external load balancer public IP address. You can find this (and the kibana public IP address) in the portal UI. Here's an example with the Kibana public IP

![kibana-public-ip](https://cloud.githubusercontent.com/assets/208231/19872869/1206c548-a010-11e6-8e12-7161fdb0556d.png)

then click it to get the IP address and DNS name:

![kibana-public-ip-details](https://cloud.githubusercontent.com/assets/208231/19872892/2d797f82-a010-11e6-898d-bbcd156be758.png)

For Kibana, you can access it by Kibana public IP address or DNS name with port `5601` and for Elasticsearch through and external load balanacer, through the external load balancer public IP address or DNS name with port `9200`.

> Finally i got the below values as output. But the problem is i cann't access the kibana url, neither cann't access the elastic search data node end point (which is nothing but the load balancer url) through sense plug-in in chrome. I configured load balancer as external

The Sense Chrome plugin is a little outdated now and the latest version as far as I can see does not send an Authorization HTTP header with credentials when a cluster is protected with Shield. Shield does not work with Authentication credentials specified as part of the URI, they must be sent using the Authorization HTTP header so if you're cluster is protected with Shield, using the Sense Chrome plugin as is will not work. Looking at the Chrome plugin source, within the function `callES` in `base.js`, the code for pulling the credentials out of the URI and constructing an Authorization header to send as part of the request is there but commented out. So, you _could_ monkey patch the `callES` function to include the commented out section (which works) but I would recommend to 

1. use the Sense plugin within the deployed Kibana which will use the login credentials behind the scenes to make the calls
2. use an Elasticsearch client or curl to make the calls, passing the authentication credentials as per the client documentation
