### ISSUE TITLE
Deployment Error: VMExtensionProvisioningError

### ISSUE THREAD

**Issue by agnelantony2** [elastic/azure-marketplace#125] opened 2017-05-18 16:36 UTC
I am trying to deploy a cluster on an existing vnet. It looks like all install scripts working successfully until it gets to last step after [port-forwarding]

```
[18052017-14:09:37] [port_forward] port forwarding configured
[18052017-14:09:42] [wait_for_started] Seeing if node is up for the after sleeping 5 seconds, retry 1/30
[18052017-14:09:47] [wait_for_started] Seeing if node is up for the after sleeping 5 seconds, retry 2/30
[18052017-14:09:53] [wait_for_started] Seeing if node is up for the after sleeping 5 seconds, retry 3/30.........
[18052017-14:12:08] [wait_for_started] never saw elasticsearch go up locally
```

Error message: "Enable failed: failed to execute command: command terminated with exit status=10

**Comment by russcam** [comment] 2017-05-19 07:13
Hey @agnelantony2, when installing X-Pack as part of the cluster, the usernames and passwords configured as part of the deployment steps for `elastic` superuser, `es_read` and `es_kibana` are added to Elasticsearch through the REST API. In order to perform this, the script has determine when Elasticsearch has started but it never saw it start in your case.

You'll be able to find more details by ssh'ing into the box on which the deployment failed by first ssh'ing into the Kibana or Jumpbox VM. Once on the target machine, take a look in the following files

- `/var/log/arm-install.log`: is the log file the template generates for the Script VM extension installation
- `/var/lib/waagent/custom-script/download/0/stdin`: is the log file that Azure generates for the Custom Script VM extension standard input
- `/var/lib/waagent/custom-script/download/0/stderr`: is the log file that Azure generates for the Custom Script VM extension standard error output

You should be able to find more details for why this has failed in your case.

Is the Elasticsearch process running on the VM when you ssh in?

**Comment by agnelantony2** [comment] 2017-05-19 16:40
This is what i see in stderr file

```
elasticsearch-ubuntu-install.sh: line 765: ntpdate: command not found
gpg: keyring `/tmp/tmphn9yb4b7/secring.gpg' created
gpg: keyring `/tmp/tmphn9yb4b7/pubring.gpg' created
gpg: requesting key EEA14886 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmphn9yb4b7/trustdb.gpg: trustdb created
gpg: key EEA14886: public key "Launchpad VLC" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
sent invalidate(group) request, exiting
sent invalidate(passwd) request, exiting
sent invalidate(group) request, exiting
sent invalidate(group) request, exiting
sent invalidate(group) request, exiting
sent invalidate(passwd) request, exiting
sent invalidate(group) request, exiting
sent invalidate(passwd) request, exiting
sent invalidate(group) request, exiting
sent invalidate(passwd) request, exiting
sent invalidate(group) request, exiting
sent invalidate(passwd) request, exiting
sent invalidate(group) request, exiting
sent invalidate(passwd) request, exiting
sent invalidate(group) request, exiting
sent invalidate(passwd) request, exiting
sent invalidate(group) request, exiting
sent invalidate(passwd) request, exiting
sent invalidate(group) request, exiting
update-rc.d: error: no runlevel symlinks to modify, aborting!
/etc/monit/monitrc:290: Include failed -- Success '/etc/monit/conf-enabled/*'
/etc/monit/monitrc:290: Include failed -- Success '/etc/monit/conf-enabled/*'
Cannot create socket to [localhost]:2812 -- Connection refused
run-parts: executing /usr/share/netfilter-persistent/plugins.d/15-ip4tables save
run-parts: executing /usr/share/netfilter-persistent/plugins.d/25-ip6tables save
```

**Comment by russcam** [comment] 2017-05-21 22:34
what about in `/var/log/arm-install.log` and `/var/lib/waagent/custom-script/download/0/stdin`?

**Comment by russcam** [comment] 2017-07-28 00:37
@agnelantony2 I'm closing this issue; feel free to reopen with additional log details provided 👍

**Closed by russcam** 2017-07-28 00:37 UTC

**Comment by josh-klassen** [comment] 2018-01-22 15:12
@russcam was there ever any root cause found for this issue? I am seeing the same thing. Errors in the logs look the same as the above. I have the arm-install.log and sterr.log files if needed and there was no stdin file created in the specific directory.

**Comment by russcam** [comment] 2018-01-22 22:43
@josh-klassen Let's discuss on #163. There was no root cause found in the ARM template for this. My suspicion is that it's an intermittent infrastructure issue.
