### ISSUE TITLE
Missing port route for external LB ?

### ISSUE THREAD

**Issue by CombatCode** [elastic/azure-marketplace#124] opened 2017-05-16 06:55 UTC
After the fresh installation via Azure Portal I'm able to connect to Kibana, but not for Elastc instance (getting timeout on port 9200 for external load balancer IP).
I was able to get response on Kibana instance from 10.0.0.7:9200 (internal elastic LB) but not from 10.0.0.7:9201. How to check if everything is configured properly ?

**Comment by russcam** [comment] 2017-05-16 07:08
It sounds like the [port forwarding rules](https://github.com/elastic/azure-marketplace/blob/master/src/scripts/elasticsearch-ubuntu-install.sh#L794-L823) on the Elasticsearch nodes may not have been applied successfully. 
The external load balancer sends traffic to the backend pool on port 9201 which is re-routed to 9200 on the VMs to process, then re-routed back out on 9201 back to the external load balancer.

If you ssh into one of the elasticsearch nodes via kibana e.g. `data-0`, and run

```
cat /etc/iptables/rules.v4
cat /etc/iptables/rules.v6
```
What do you see?

**Comment by CombatCode** [comment] 2017-05-16 07:17
@russcam thank you for the fast response :) 
I miss the fact that internal load balancer has no rules for port 9201 so it's ok that I get nothing.
Connecting from kibana directly to data-1 (10.0.0.12) via port 9201 works good, I see also at arm logs that port forwarding was initialized.

```
combat@el-data-1:~$ cat /etc/iptables/rules.v4
cat: /etc/iptables/rules.v4: Permission denied
combat@el-data-1:~$ sudo cat /etc/iptables/rules.v4
# Generated by iptables-save v1.6.0 on Mon May 15 19:39:43 2017
*nat
:PREROUTING ACCEPT [3:152]
:INPUT ACCEPT [6:304]
:OUTPUT ACCEPT [8:539]
:POSTROUTING ACCEPT [8:539]
-A PREROUTING -p tcp -m tcp --dport 9201 -j REDIRECT --to-ports 9200
-A OUTPUT -o lo -p tcp -m tcp --dport 9201 -j REDIRECT --to-ports 9200
COMMIT
# Completed on Mon May 15 19:39:43 2017
# Generated by iptables-save v1.6.0 on Mon May 15 19:39:43 2017
*filter
:INPUT ACCEPT [502551:730816844]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [183042:9809793]
-A INPUT -p udp -m udp --dport 68 -j ACCEPT
COMMIT
# Completed on Mon May 15 19:39:43 2017
```
Seems ok, right? 

But as I see at the Azure, external-lb-ip is 52.233.192.249 (associated with external-lb) but still getting timeout opening http://52.233.192.249:9200 , any idea what can I verify?

**Comment by russcam** [comment] 2017-05-16 07:33
Looks ok to me.

If you can make a request to all nodes in the cluster from kibana on port 9201 then it sounds like something has gone wrong with the external LB deployment/configuration. Is there anything in its audit logs? 

If you don't have any data in the cluster yet, could you try redeploying again?

**Comment by CombatCode** [comment] 2017-05-16 09:42
I have figured out that this issue is not related to LB or the data instance.
Probably wrong elasticsearch configuration which is not allowing to access from the outside?  

```
root@el-data-0:/home/combat# cat /etc/elasticsearch/elasticsearch.yml
cluster.name: production-urstyle-elastic
node.name: el-data-0
path.data: /datadisks/disk1/elasticsearch/data
discovery.zen.ping.unicast.hosts: ["el-master-0:9300","el-master-1:9300","el-master-2:9300"]
node.master: false
node.data: true
discovery.zen.minimum_master_nodes: 2
network.host: [_site_, _local_]
node.max_local_storage_nodes: 1
```

netstat -l
```
tcp6       0      0 10.0.0.14:9200          [::]:*                  LISTEN
tcp6       0      0 localhost:9200          [::]:*                  LISTEN
tcp6       0      0 ip6-localhost:9200      [::]:*                  LISTEN
tcp6       0      0 10.0.0.14:9300          [::]:*                  LISTEN
tcp6       0      0 localhost:9300          [::]:*                  LISTEN
tcp6       0      0 ip6-localhost:9300      [::]:*                  LISTEN
```
Idk, but shouldn't be a 0.0.0.0 instead of localhost? @russcam

**Comment by CombatCode** [comment] 2017-05-16 10:17
New fresh installation - same issue, 9200 is not accessible for external IP

**Comment by russcam** [comment] 2017-05-16 12:22
@CombatCode I just deployed a cluster from the portal with an external load balancer and all is working as expected.

Would you be able to share your deployment parameters (redact any sensitive ones)?

**Comment by CombatCode** [comment] 2017-05-17 08:01
@russcam Can I extract somehow this parameters from azure?
This is a basic installation with all default options selected except the LB type (external instead of internal)... and data instance type (I'm using Standard DS1 (1 core, 3.5 GB memory) instead of default DS1_V2 because of quota exceeded)

**Comment by russcam** [comment] 2017-05-19 07:52
There's no nice way to be able to extract the parameters post deployment as far as I know, but you can download them from the portal before deploying with

![screen shot 2017-05-19 at 5 49 36 pm](https://cloud.githubusercontent.com/assets/208231/26238313/def4ba18-3cbb-11e7-9425-b48bef5f219b.png)

and selecting the `parameters` tab

![screen shot 2017-05-19 at 5 50 00 pm](https://cloud.githubusercontent.com/assets/208231/26238319/e6985c48-3cbb-11e7-89f2-dacf336f8b0f.png)

**Comment by russcam** [comment] 2017-05-30 05:26
Have you been able to look at this further, @CombatCode?

**Comment by CombatCode** [comment] 2017-06-16 12:14
@russcam I will back to this in a few days and let u know

**Comment by CombatCode** [comment] 2017-06-21 20:06
@russcam Fresh installation, still the same issue,
there you have may installation parameters:

```
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "esVersion": {
            "value": "5.4.0"
        },
        "esClusterName": {
            "value": "elastic"
        },
        "azureCloudPlugin": {
            "value": "No"
        },
        "azureCloudStorageAccountName": {
            "value": ""
        },
        "azureCloudStorageAccountKey": {
            "value": null
        },
        "xpackPlugins": {
            "value": "Yes"
        },
        "esAdditionalPlugins": {
            "value": ""
        },
        "loadBalancerType": {
            "value": "external"
        },
        "vNetNewOrExisting": {
            "value": "existing"
        },
        "vNetName": {
            "value": "network"
        },
        "vNetClusterSubnetName": {
            "value": "network"
        },
        "vNetLoadBalancerIp": {
            "value": "10.0.0.7"
        },
        "vNetExistingResourceGroup": {
            "value": "production-urstyle-db"
        },
        "vNetNewClusterSubnetAddressPrefix": {
            "value": "10.0.0.0/24"
        },
        "vNetAppGatewaySubnetName": {
            "value": "es-gateway-subnet"
        },
        "vNetNewAppGatewaySubnetAddressPrefix": {
            "value": "10.0.0.128/28"
        },
        "kibana": {
            "value": "Yes"
        },
        "vmSizeKibana": {
            "value": "Standard_D1"
        },
        "kibanaKeyBlob": {
            "value": null
        },
        "kibanaCertBlob": {
            "value": ""
        },
        "kibanaKeyPassphrase": {
            "value": null
        },
        "jumpbox": {
            "value": "No"
        },
        "vmSizeDataNodes": {
            "value": "Standard_DS1_v2"
        },
        "vmDataDiskCount": {
            "value": 40
        },
        "vmDataDiskSize": {
            "value": "Large"
        },
        "vmDataNodeCount": {
            "value": 3
        },
        "storageAccountType": {
            "value": "Default"
        },
        "dataNodesAreMasterEligible": {
            "value": "No"
        },
        "vmHostNamePrefix": {
            "value": "els"
        },
        "vmSizeMasterNodes": {
            "value": "Standard_D1"
        },
        "vmClientNodeCount": {
            "value": 0
        },
        "adminUsername": {
            "value": "combat"
        },
        "authenticationType": {
            "value": "sshPublicKey"
        },
        "sshPublicKey": {
            "value": null
        },
        "securityAdminPassword": {
            "value": null
        },
        "securityReadPassword": {
            "value": null
        },
        "securityKibanaPassword": {
            "value": null
        },
        "appGatewayTier": {
            "value": "Standard"
        },
        "appGatewaySku": {
            "value": "Small"
        },
        "appGatewayCount": {
            "value": 1
        },
        "appGatewayCertBlob": {
            "value": ""
        },
        "appGatewayCertPassword": {
            "value": null
        },
        "appGatewayWafStatus": {
            "value": "Disabled"
        },
        "appGatewayWafMode": {
            "value": "Detection"
        },
        "location": {
            "value": "westeurope"
        },
        "userCompany": {
            "value": "BiznesIT"
        },
        "userEmail": {
            "value": "xxx@xxx.pl"
        },
        "userFirstName": {
            "value": "Damian"
        },
        "userLastName": {
            "value": "Gądziak"
        },
        "userJobTitle": {
            "value": "IT Executive (CIO, CTO, VP Engineering, etc.)"
        },
        "userCountry": {
            "value": "Poland"
        }
    }
}
```

External load balancer informations:
production-urstyle-elastic
IP address
52.233.224.243
Location
West Europe
DNS name
lb-5gbpqwzulmes2.westeurope.cloudapp.azure.com
Subscription name
(change)
BizSpark
Associated to
es-external-lb

as you can see, http://52.233.224.243:9200 is not working 👎

**Comment by russcam** [comment] 2017-06-25 23:57
Thanks for the parameters @CombatCode, looking at this now

**Comment by russcam** [comment] 2017-06-26 01:18
I can't replicate what you're experiencing @CombatCode. Here's the steps I took to replicate: 

Using the following parameters file based on the one provided (`null` values need to be replaced with `""` - a quirk of exporting the template where values are secure strings):

```json
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "esVersion": {
            "value": "5.4.0"
        },
        "esClusterName": {
            "value": "elastic"
        },
        "azureCloudPlugin": {
            "value": "No"
        },
        "azureCloudStorageAccountName": {
            "value": ""
        },
        "azureCloudStorageAccountKey": {
            "value": ""
        },
        "xpackPlugins": {
            "value": "Yes"
        },
        "esAdditionalPlugins": {
            "value": ""
        },
        "loadBalancerType": {
            "value": "external"
        },
        "vNetNewOrExisting": {
            "value": "existing"
        },
        "vNetName": {
            "value": "network"
        },
        "vNetClusterSubnetName": {
            "value": "network"
        },
        "vNetLoadBalancerIp": {
            "value": "10.0.0.7"
        },
        "vNetExistingResourceGroup": {
            "value": "production-urstyle-db"
        },
        "vNetNewClusterSubnetAddressPrefix": {
            "value": "10.0.0.0/24"
        },
        "vNetAppGatewaySubnetName": {
            "value": "es-gateway-subnet"
        },
        "vNetNewAppGatewaySubnetAddressPrefix": {
            "value": "10.0.0.128/28"
        },
        "kibana": {
            "value": "Yes"
        },
        "vmSizeKibana": {
            "value": "Standard_D1"
        },
        "kibanaKeyBlob": {
            "value": ""
        },
        "kibanaCertBlob": {
            "value": ""
        },
        "kibanaKeyPassphrase": {
            "value": ""
        },
        "jumpbox": {
            "value": "No"
        },
        "vmSizeDataNodes": {
            "value": "Standard_DS1_v2"
        },
        "vmDataDiskCount": {
            "value": 40
        },
        "vmDataDiskSize": {
            "value": "Large"
        },
        "vmDataNodeCount": {
            "value": 3
        },
        "storageAccountType": {
            "value": "Default"
        },
        "dataNodesAreMasterEligible": {
            "value": "No"
        },
        "vmHostNamePrefix": {
            "value": "els"
        },
        "vmSizeMasterNodes": {
            "value": "Standard_D1"
        },
        "vmClientNodeCount": {
            "value": 0
        },
        "adminUsername": {
            "value": "russ"
        },
        "authenticationType": {
            "value": "sshPublicKey"
        },
        "sshPublicKey": {
            "value": "<redacted>"
        },
        "securityAdminPassword": {
            "value": "<redacted>"
        },
        "securityReadPassword": {
            "value": "<redacted>"
        },
        "securityKibanaPassword": {
            "value": "<redacted>"
        },
        "appGatewayTier": {
            "value": "Standard"
        },
        "appGatewaySku": {
            "value": "Small"
        },
        "appGatewayCount": {
            "value": 1
        },
        "appGatewayCertBlob": {
            "value": ""
        },
        "appGatewayCertPassword": {
            "value": ""
        },
        "appGatewayWafStatus": {
            "value": "Disabled"
        },
        "appGatewayWafMode": {
            "value": "Detection"
        },
        "location": {
            "value": "westeurope"
        },
        "userCompany": {
            "value": "Elastic"
        },
        "userEmail": {
            "value": "<redacted>"
        },
        "userFirstName": {
            "value": "Russ"
        },
        "userLastName": {
            "value": "Cam"
        },
        "userJobTitle": {
            "value": "IT Executive (CIO, CTO, VP Engineering, etc.)"
        },
        "userCountry": {
            "value": "Australia"
        }
    }
}
```
1. First, I set up the existing virtual network in another resource group in the same location:

![screenshot 2017-06-26 10 27 51](https://user-images.githubusercontent.com/208231/27521285-714bf592-5a5e-11e7-95ef-203597c0b295.png)

2. logged into azure CLI:

    ```sh
    azure login
    ```
3. switched to arm mode

    ```sh
    azure config mode arm
    ```

4. created the resource group for the deployment

    ```sh
    azure group create russ-cluster westeurope
    ```

5. deployed from the `master` branch to the created resource group, using the template parameters above

    ```sh
    azure group deployment create --template-uri https://raw.githubusercontent.com/elastic/azure-marketplace/master/src/mainTemplate.json --parameters-file parameters/ssh.parameters.json -g russ-cluster
    ```
6. output from successful deployment

    ```sh
	data:    DeploymentName     : mainTemplate
	data:    ResourceGroupName  : russ-cluster
	data:    ProvisioningState  : Succeeded
	data:    Timestamp          : Mon Jun 26 2017 10:51:21 GMT+1000 (AUS Eastern Standard Time)
	data:    Mode               : Incremental
	data:    CorrelationId      : <redacted>
	data:    TemplateLink       : https://raw.githubusercontent.com/elastic/azure-marketplace/master/src/mainTemplate.json data:    ContentVersion     : 1.0.0.0
	data:    DeploymentParameters :
	data:    Name                                  Type          Value

	data:    ------------------------------------  ------------  ----------------------------------------------------------------------
	data:    artifactsBaseUrl                      String        https://raw.githubusercontent.com/elastic/azure-marketplace/master/src
	data:    elasticTags                           Object        [object Object]

	data:    esVersion                             String        5.4.0

	data:    esClusterName                         String        elastic

	data:    loadBalancerType                      String        external

	data:    azureCloudPlugin                      String        No

	data:    azureCloudStorageAccountName          String

	data:    azureCloudStorageAccountKey           SecureString  undefined

	data:    xpackPlugins                          String        Yes

	data:    esAdditionalPlugins                   String

	data:    kibana                                String        Yes

	data:    vmSizeKibana                          String        Standard_D1

	data:    kibanaCertBlob                        String

	data:    kibanaKeyBlob                         SecureString  undefined

	data:    kibanaKeyPassphrase                   SecureString  undefined

	data:    jumpbox                               String        No

	data:    vmHostNamePrefix                      String        els

	data:    vmSizeDataNodes                       String        Standard_DS1_v2

	data:    vmDataDiskCount                       Int           40

	data:    vmDataDiskSize                        String        Large

	data:    vmDataNodeCount                       Int           3

	data:    storageAccountType                    String        Default

	data:    dataNodesAreMasterEligible            String        No

	data:    vmSizeMasterNodes                     String        Standard_D1

	data:    vmClientNodeCount                     Int           0

	data:    vmSizeClientNodes                     String        Standard_D1

	data:    adminUsername                         String        russ

	data:    authenticationType                    String        sshPublicKey

	data:    adminPassword                         SecureString  undefined

	data:    sshPublicKey                          SecureString  undefined

	data:    securityAdminPassword                 SecureString  undefined

	data:    securityReadPassword                  SecureString  undefined

	data:    securityKibanaPassword                SecureString  undefined

	data:    location                              String        westeurope

	data:    vNetNewOrExisting                     String        existing

	data:    vNetName                              String        network

	data:    vNetExistingResourceGroup             String        production-urstyle-db

	data:    vNetNewAddressPrefix                  String        10.0.0.0/24

	data:    vNetLoadBalancerIp                    String        10.0.0.7

	data:    vNetClusterSubnetName                 String        network

	data:    vNetNewClusterSubnetAddressPrefix     String        10.0.0.0/24

	data:    vNetAppGatewaySubnetName              String        es-gateway-subnet

	data:    vNetNewAppGatewaySubnetAddressPrefix  String        10.0.0.128/28

	data:    appGatewayTier                        String        Standard

	data:    appGatewaySku                         String        Small

	data:    appGatewayCount                       Int           1

	data:    appGatewayCertBlob                    String

	data:    appGatewayCertPassword                SecureString  undefined

	data:    appGatewayWafStatus                   String        Disabled

	data:    appGatewayWafMode                     String        Detection

	data:    userCompany                           String        Elastic

	data:    userEmail                             String        <redacted>

	data:    userFirstName                         String        Russ

	data:    userLastName                          String        Cam

	data:    userJobTitle                          String        IT Executive (CIO, CTO, VP Engineering, etc.)

	data:    userCountry                           String        Australia

	data:    Outputs            :
	data:    Name          Type    Value
	data:    ------------  ------  ----------------------------------------------------------
	data:    loadbalancer  String  http://lb-23nxasf2nsmtm.westeurope.cloudapp.azure.com:9200
	data:    kibana        String  http://kb-23nxasf2nsmtm.westeurope.cloudapp.azure.com:5601
	data:    jumpboxssh    String  N/A
	info:    group deployment create command OK
    ```
7. navigating to `http://lb-23nxasf2nsmtm.westeurope.cloudapp.azure.com:9200` and after logging in with `elastic` and password supplied in template for `securityAdminPassword`, I can successfully access the cluster externally:

![screenshot 2017-06-26 10 53 40](https://user-images.githubusercontent.com/208231/27521373-6cd93e10-5a5f-11e7-9fbf-cf8d7b89c9cc.png)

Further questions:

1. Does the deployment succeed?
2. Do you have any network security rules in place that may be preventing you from accessing the external LB public IP?

**Comment by russcam** [comment] 2017-07-14 05:59
Have you had a chance to look at this again @CombatCode?

**Comment by russcam** [comment] 2017-07-28 00:38
@CombatCode I'm closing this issue as I've been unable to reproduce after many attempts. Feel free to reopen if additional details come to light 👍

**Closed by russcam** 2017-07-28 00:38 UTC
