### ISSUE TITLE
VMExtensionProvisioningError deployment error

### ISSUE THREAD

**Issue by Ilya128** [elastic/azure-marketplace#108] opened 2017-04-07 00:29 UTC
Hello,
I tried to deploy using powershell based on the supplied example, with the following parameters object:
$clusterParameters = @{
    "esClusterName" = "elastic-weus1"
    "xpackPlugins" = "No"
    "dataNodesAreMasterEligible" = "Yes"
    "adminUsername" = "admin"
    "adminPassword" = "********************"
    "securityAdminPassword" = "**********"
    "securityReadPassword" = "**********"
    "securityKibanaPassword" = "**********"
    "location" = "westeurope"
}

Deployment of all data node VMs failed with the following error:
statusCode:Conflict statusMessage:{"status":"Failed","error":{"code":"ResourceDeploymentFailure","message":"The resource operation completed with terminal provisioning state 'Failed'.","details":[{"code":"VMExtensionProvisioningError","message":"VM has reported a failure when processing extension 'script'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=2\"."}]}}

* Note that deployment of Kibana VM succeeded.

Please assist,
Ilya

**Comment by Mpdreamz** [comment] 2017-04-07 16:43
Hmm this looks off exit code `2` is reserved for showing help:

https://github.com/elastic/azure-marketplace/blob/master/src/scripts/elasticsearch-ubuntu-install.sh#L169

Next week we are going to have another pass over the template and fixing outstanding issues. We'll definitely take this one on board.

**Comment by tibbing** [comment] 2017-04-10 08:30
Same issue here, not possible to deploy from within portal or using ARM.

**Comment by russcam** [comment] 2017-04-11 03:19
Thanks for reporting @Ilya128 and @tibbing. I'm looking at this now. 

Do you have additional deployment details for the failure, either from the portal or from the deployment log on the VM? The portal deployment details can be found by navigating via

![Deployment error details](https://raw.githubusercontent.com/elastic/azure-marketplace/master/images/error-output.png)

The deployment log for the template can be found on the VM deployed to at 
```
/var/log/arm-install.log
```

respectively

**Comment by russcam** [comment] 2017-04-11 06:12
One thing that will cause it to fail is that `admin` is not an allowed Admin Username. [**See this list for invalid admin usernames**](https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-usernames/#ubuntu). _I'm fairly sure_ this gets caught **before** the deployment script runs though, upon provisioning the VM, so wouldn't cause the VMExtensionProvisioning error you saw.

I just ran a deployment with the following parameters:

```powershell
$templateVersion = "c0664f94de618501c0662d50c89c008cd69906e1"
$elasticTemplate = "https://raw.githubusercontent.com/elastic/azure-marketplace/$templateVersion/src/mainTemplate.json"
$location = "westeurope"
$resourceGroup = "vm-provisioning"
$name = $resourceGroup

$clusterParameters = @{
  "artifactsBaseUrl"="https://raw.githubusercontent.com/elastic/azure-marketplace/$templateVersion/src"
  "esClusterName" = $name
  "xpackPlugins" = "No"
  "dataNodesAreMasterEligible" = "Yes"
  "adminUsername" = "russ"
  "adminPassword" = "Password1234"
  "securityAdminPassword" = ""
  "securityReadPassword" = ""
  "securityKibanaPassword" = ""
  "location" = "westeurope"
}

Write-Host "[$(Get-Date -format 'u')] Deploying cluster"
New-AzureRmResourceGroup -Name $resourceGroup -Location $location
New-AzureRmResourceGroupDeployment -Name $name -ResourceGroupName $resourceGroup -TemplateUri $elasticTemplate -TemplateParameterObject $clusterParameters
Write-Host "[$(Get-Date -format 'u')] Deployed cluster"
```
`c0664f94de618501c0662d50c89c008cd69906e1` is the git commit prior to a PR that was just merged in. This failed with exit code 1

```
{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.",
        "details": [
          {
            "code": "Conflict",
            "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'script'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=1\\\".\"\r\n      }\r\n    ]\r\n  }\r\n}"
          }
        ]
      }
    ]
  }
}
```

Digging into the details on the VM, it isn't clear why this failed. I suspect it's due to the security* passwords being empty and the parameter values not being quoted when passed to the bash deployment script. Re-running the same script replacing `$templateVersion` value with `"master"`, which does quote security* password values, the cluster **successfully deploys.** 

@Ilya128, would you be able to try your deployment again, targeting `$templateVersion = "78ed10d63b2f5fe040015c6feb954f39e8c3698f"` (latest master at this time)?

@tibbing, The portal always deploys with X-Pack plugins installed and security passwords are enforced to be required in the Portal UI, so the above issue would not affect a portal deployment. Could you provide more detail on the error message you get in the portal, and the parameters that you're using?

**Comment by funrockstefan** [comment] 2017-04-11 09:42
(colleague to @tibbing)
**Error messages reported when deploying via portal:**
{
	"status": "Failed",
	"error": {
		"code": "ResourceDeploymentFailure",
		"message": "The resource operation completed with terminal provisioning state 'Failed'.",
		"details": [{
				"code": "DeploymentFailed",
				"message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.",
				"details": [{
						"code": "Conflict",
						"message": {
							"status": "Failed",
							"error": {
								"code": "ResourceDeploymentFailure",
								"message": "The resource operation completed with terminal provisioning state 'Failed'.",
								"details": [{
										"code": "VMExtensionProvisioningError",
										"message": "VM has reported a failure when processing extension 'script'. Error message: " Enable failed: failed to execute command: command terminated with exit status = 2"
									}
								]
							}
						}
					}
				]
			}
		]
	}
}



Summary of the parameters :
Basics
Subscription
hidden
Resource group
hidden
Location
West Europe
User name
hidden
Password
****************
Cluster Settings
Elasticsearch version
v5.1.2
Cluster name
hidden
Virtual network
es-net
subnet
es-subnet
subnet address prefix
10.3.0.0/24
Nodes Configuration
Hostname prefix
vm-
Number of data nodes (if not using dedicated masters, >= 3 data nodes)
3
Data node VM size
Standard DS1 v2
Data nodes are master eligible
No
Master node VM size
Standard D1
Number of client nodes
2
Client node VM size
Standard D1
User Configuration
(es_admin or elastic) password
****************
es_read Password
****************
es_kibana Password
****************
External Access Control
Install Kibana?
Yes
Kibana VM size
Standard D1
Use a jump box?
No
Load balancer type
External
User Information
Company
hidden
Email address
hidden
First name
hidden
Last Name
hidden
Job title
IT Executive (CIO, CTO, VP Engineering, etc.)
Country
SWEDEN

**Comment by funrockstefan** [comment] 2017-04-11 15:31
The script works only when xpackPlugins is set to "No", however we would like to use X-Pack, any idea how we can make it work?

**Comment by russcam** [comment] 2017-04-11 23:23
Thanks for the details for the portal deployment, @funrockstefan. I'm looking at this now. 

With the template deployment, what parameters are you using?

**Comment by funrockstefan** [comment] 2017-04-12 07:10
Template parameters when it fails:
(If we change xpackPlugins to "No" it works fine)

$templateVersion = "c0664f94de618501c0662d50c89c008cd69906e1"

$parameters.Add(“artifactsBaseUrl”, "https://raw.githubusercontent.com/elastic/azure-marketplace/$templateVersion/src")
$parameters.Add(“esVersion”, "5.1.2")
$parameters.Add(“esClusterName”, [hidden])
$parameters.Add(“azureCloudPlugin”, "No")
$parameters.Add(“xpackPlugins”, "Yes")
$parameters.Add(“esAdditionalPlugins”, "")
$parameters.Add(“loadBalancerType”, "internal")
$parameters.Add(“vNetNewOrExisting”, "new")
$parameters.Add(“vNetName”,  "$clusterName-net")
$parameters.Add(“vNetClusterSubnetName”, "$clusterName-subnet")
$parameters.Add(“vNetLoadBalancerIp”, "10.3.0.4")
$parameters.Add(“vNetExistingResourceGroup”, $resourceGroupName)
$parameters.Add(“vNetNewAddressPrefix”, "10.3.0.0/16")
$parameters.Add(“vNetNewClusterSubnetAddressPrefix”, "10.3.0.0/24")
$parameters.Add(“kibana”, "Yes")
$parameters.Add(“jumpbox”, "No")
$parameters.Add(“vmSizeDataNodes”, "Standard_DS2_v2")
$parameters.Add(“vmDataNodeCount”, 3)
$parameters.Add(“dataNodesAreMasterEligible”, "No")
$parameters.Add(“vmHostNamePrefix”, "eaavm")
$parameters.Add(“vmSizeMasterNodes”, "Standard_D2_v2")
$parameters.Add(“vmClientNodeCount”, 2)
$parameters.Add(“vmSizeClientNodes”, "Standard_D1_v2")
$parameters.Add(“vmSizeKibana”, "Standard_D1_v2")
$parameters.Add(“adminUsername”, [hidden])
$parameters.Add(“authenticationType”, "password")
$parameters.Add(“adminPassword”, [hidden])
$parameters.Add(“securityAdminPassword”, [hidden])
$parameters.Add(“securityReadPassword”, [hidden])
$parameters.Add(“securityKibanaPassword”, [hidden])
$parameters.Add(“location”, "westeurope")
$parameters.Add(“userCompany”, [hidden])
$parameters.Add(“userEmail”, [hidden])
$parameters.Add(“userFirstName”, [hidden])
$parameters.Add(“userLastName”, [hidden])
$parameters.Add(“userJobTitle”, "IT Executive (CIO, CTO, VP Engineering, etc.)")
$parameters.Add(“userCountry”, "Sweden")

**Comment by russcam** [comment] 2017-04-12 08:43
Thanks @funrockstefan.

I ran a few deployments from the portal earlier with the portal parameters you provided, and they all deployed successfully. I'm keen to get to find out what the issue is here though; with a failed portal deployment, would you be able to ssh into one of the failed VM script deployment boxes and provide the (obsfucated out sensitive data)  contents of `/var/log/arm-install.log`?

Could you try your parameters above targeting `master` i.e.

```sh
$templateVersion = "master"
```
and let me know the outcome?

**Comment by funrockstefan** [comment] 2017-04-12 09:50
Good news: Script and Template now works, thanks for your help @russcam

**Comment by russcam** [comment] 2017-04-13 00:22
That's good to hear @funrockstefan 😃 

@Ilya128, could you also try with `$templateVersion = dec7dde7cbdf49f611dea778e9f479edd51cd335` _(latest master)_ ?

**Comment by russcam** [comment] 2017-05-06 01:11
Closing this as no additional feedback received.

Feel free to reopen if the problem still exists 👍

**Closed by russcam** 2017-05-06 01:11 UTC
Labels: bug
