### ISSUE TITLE
Unable to parse parameter: "attributes"

### ISSUE THREAD

**Issue by smarshal-Quest** [elastic/azure-marketplace#288] opened 2019-06-11 11:38 UTC
Receiving above error when deploying template using Azure CLI 

```sh
template_version="6.8.0"
template_url="https://raw.githubusercontent.com/elastic/azure-marketplace/master/src"
elastic_template=$template_url/mainTemplate.json

az group deployment create \
    --name $name \
    --resource-group $resource_group \
    --template-uri $elastic_template \
    --parameters artifactsBaseUrl=$template_url \
                 esVersion=$template_version \
                 dataNodesAreMasterEligible=Yes \
                 loadBalancerType=external \
                 vmDataNodeCount=3 \
                 vmDataDiskSize=32GiB \
                 vmDataDiskCount=1 \
                 vmClientNodeCount=0 \
                 esClusterName=$name \
                 esHttpCertBlob=$http_cert \
                 esTransportCaCertBlob=$http_ca \
                 adminUsername=$admin_user \
                 authenticationType=sshPublicKey \
                 sshPublicKey="$sshPublicKey" \
                 kibanaCertBlob=$kibana_cert \
                 kibanaKeyBlob=$kibana_key \
                 samlMetadataUri=$metadata_uri \
                 adminPassword=$adminPassword \
                securityAdminPassword=$securityAdminPassword \
                securityApmPassword=$securityApmPassword \
                securityBootstrapPassword=$securityBootstrapPassword \
                securityBeatsPassword=$securityBeatsPassword \
                securityKibanaPassword=$securityKibanaPassword \
                securityLogstashPassword=$securityLogstashPassword \
                samlServiceProviderUri=$samlServiceProviderUri
```

**Comment by russcam** [comment] 2019-06-11 23:03
Hi @smarshal-Quest , do you have the deployment error output, either from the CLI or from within the Deployments sub menu for the target resource group?

**Comment by russcam** [comment] 2019-06-12 05:35
I also see that you're deploying from the master branch. This is not recommended because it may contain changes that are not yet released, which currently includes 6.8.0. I would recommend using a tagged release e.g. https://github.com/elastic/azure-marketplace/tree/7.0.0

7.1.1 and 6.8.0 release should be going out shortly, if you'd prefer to wait for these

**Comment by smarshal-Quest** [comment] 2019-06-12 06:27
Hi Ross

I am seeing same issue when pinning to 7.0.0 tag.

In portal Deployment doesn’t start
Cli output :
Unable to parse parameter: "attributes"

Az cli version:

az -v
azure-cli                         2.0.66

acr                                2.2.8
acs                                2.4.3
advisor                            2.0.0
ams                                0.4.6
appservice                        0.2.20
backup                             1.2.4
batch                              4.0.2
batchai                            0.4.9
billing                            0.2.1
botservice                         0.2.1
cdn                                0.2.3
cloud                              2.1.1
cognitiveservices                  0.2.5
command-modules-nspkg               2.0.2
configure                         2.0.23
consumption                        0.4.3
container                         0.3.17
core                              2.0.66
cosmosdb                          0.2.10
deploymentmanager                  0.1.0
dla                                0.2.5
dls                                0.1.9
dms                                0.1.3
eventgrid                          0.2.3
eventhubs                          0.3.6
extension                          0.2.5
feedback                           2.2.1
find                               0.3.3
hdinsight                          0.3.4
interactive                        0.4.4
iot                               0.3.10
iotcentral                         0.1.6
keyvault                          2.2.15
kusto                              0.2.2
lab                                0.1.7
maps                               0.3.4
monitor                           0.2.14
natgateway                         0.1.0
network                            2.5.1
nspkg                              3.0.3
policyinsights                     0.1.3
privatedns                         1.0.1
profile                            2.1.5
rdbms                             0.3.11
redis                              0.4.3
relay                              0.1.4
reservations                       0.4.2
resource                          2.1.15
role                               2.6.3
search                             0.1.1
security                           0.1.1
servicebus                         0.3.5
servicefabric                     0.1.19
signalr                            1.0.0
sql                                2.2.4
sqlvm                              0.1.1
storage                            2.4.2
telemetry                          1.0.2
vm                                2.2.22

Python location '/usr/local/Cellar/azure-cli/2.0.66/libexec/bin/python'
Extensions directory '/Users/shaun/.azure/cliextensions'

Python (Darwin) 3.7.3 (default, Mar 27 2019, 09:23:15)
[Clang 10.0.1 (clang-1001.0.46.3)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.



Regards
Shaun

**Comment by smarshal-Quest** [comment] 2019-06-12 10:19
I have managed to resolve the issue
reverted back to 6.7.0 then discovered the default value for the parameter vmSizeDataNodes fails as size not available.  Keeping the Parameter override and running 7.0.0 , works with no errors

**Comment by russcam** [comment] 2019-06-12 10:23
Good to hear @smarshal-Quest  :+1: There are infrequently some changes to parameters for the template, in even more infrequently, some values. I would recommend to always [check the release notes](https://github.com/elastic/azure-marketplace/releases) for a version as we try our best to call these out.

I'm going to close this as the issue is resolved

**Closed by russcam** 2019-06-12 10:23 UTC
