### ISSUE TITLE
Provisioning endless loop....

### ISSUE THREAD

**Issue by niemyjski** [elastic/azure-marketplace#106] opened 2017-03-27 19:41 UTC
So I just wanted to provision a single node into a new resource group and somehow the script was in an endless loop on master...
![screen shot 2017-03-27 at 2 37 27 pm](https://cloud.githubusercontent.com/assets/1020579/24374602/1790ad22-12fb-11e7-8db5-367890a4183e.png)

```json
{
	"artifactsBaseUrl":{"value":"https://raw.githubusercontent.com/elastic/azure-marketplace/master/src"},
	"esVersion":{"value":"5.1.2"},
	"esClusterName":{"value":"ex-test-es"},
	"location":{"value":"ResourceGroup"},
	"xpackPlugins":{"value":"Yes"},
	"esAdditionalPlugins": { "value": "mapper-size" },
	"azureCloudPlugin":{"value":"Yes"},
	"azureCloudStorageAccountName":{"value":"test"},
	"azureCloudStorageAccountKey":{"value":"test=="},
	"loadBalancerType":{"value":"internal"},
	"kibana":{"value":"Yes"},
	"jumpbox":{"value":"No"},
	"vmHostNamePrefix":{"value":"test-"},
	"vmSizeKibana":{"value":"Standard_DS1_v2"},
	"vmSizeDataNodes":{"value":"Standard_DS11_v2"},
	"vmDataNodeCount":{"value":1},
	"vmDataDiskCount":{"value":1},
	"vmDataDiskSize":{"value":"Medium"},
	"storageAccountType":{"value":"Default"},
	"dataNodesAreMasterEligible":{"value":"Yes"},
	"vmSizeMasterNodes":{"value":"Standard_DS1_v2"},
	"vmClientNodeCount":{"value":0},
	"vmSizeClientNodes":{"value":"Standard_DS1_v2"},
	"adminUsername":{"value":"test"},
	"authenticationType":{"value":"sshPublicKey"},
	"sshPublicKey":{"value":"ssh-rsa testtttttt test"},
	"adminPassword":{"value":"<value-ignored>"},
	"securityAdminPassword":{"value":"testtttttt"},
	"securityReadPassword":{"value":"testtttttt"},
	"securityKibanaPassword":{"value":"testtttttt"},
	"vNetName": {"value": "test-net"},
	"vNetClusterSubnetName": {"value": "test-subnet"},
	"vNetAppGatewaySubnetName": {"value": "test-gateway"},
	"vNetLoadBalancerIp": {"value": "10.0.0.4"},
	"vNetNewOrExisting": {"value":"new"},
	"vNetExistingResourceGroup": {"value": "testtttttt-test"},
	"vNetNewAddressPrefix": {"value": "10.0.0.0/24"},   
	"vNetNewClusterSubnetAddressPrefix": {"value": "10.0.0.0/25"},
	"vNetNewAppGatewaySubnetAddressPrefix": {"value": "10.0.0.128/28"},
	"appGatewayTier": {"value":"Standard"},
	"appGatewaySku": {"value":"Small"},
	"appGatewayCount": {"value":1},
	"appGatewayCertBlob": {"value":""},
	"appGatewayCertPassword": {"value":""},
	"appGatewayWafStatus": {"value":"Disabled"},
	"appGatewayWafMode": {"value":"Detection"},
	"userCompany": { "value": "testtttttt" },
	"userEmail": { "value": "team@testtttttt.io" },
	"userFirstName": { "value": "testtttttt" },	
	"userLastName": { "value": "Support" },
	"userJobTitle": { "value": "Architect" },
	"userCountry": { "value": "US" }	
}
```

**Comment by russcam** [comment] 2017-04-18 06:44
Never seen this happen before. Have you experienced again since opening this?

**Comment by niemyjski** [comment] 2017-04-18 15:35
I haven't had to deploy anything since I ran into this but it definitely occurred. I just ran the following configs using the cli. I can get you any more info that you may need like cli version, just let me know.

**Comment by russcam** [comment] 2017-05-06 01:05
Closing this as I can't reproduce. Feel free to reopen with further details if it happens again @niemyjski 👍

**Closed by russcam** 2017-05-06 01:05 UTC
